---
- name: Install common
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Docker host
  hosts: docker.home.remigourdon.net
  become: yes
  vars_files: vars/cloudflare.yml
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - traefik
        - unifi
        - heimdall