---
- name: Install common
  hosts: all
  become: yes
  roles:
    - role: common
    - role: update
      tags: update,never

- name: Setup tailscale
  hosts: tailscale
  become: yes
  tasks:
    - name: Configure Sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        ignoreerrors: true
        sysctl_set: true
      when: tailscale_subnet_router
    - name: Configure Tailscale
      include_role:
        name: artis3n.tailscale

- name: Setup Docker on Raspberry Pi
  hosts: froufrou.home.remigourdon.net
  become: yes
  vars:
    docker_version: latest
    docker_install_compose: true
    docker_users:
      - pi
    pip_package: python3-pip
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm

- name: Setup Pi-hole on Raspberry Pi
  hosts: froufrou.home.remigourdon.net
  become: yes
  vars_files:
    - vars/pi-hole.yml
  roles:
    - role: docker-compose
      project_names:
        - pi-hole

- name: Setup Docker on Endeavour
  hosts: endeavour.home.remigourdon.net
  become: yes
  vars:
    docker_version: latest
    docker_install_compose: true
    docker_users:
      - remi
    pip_package: python3-pip
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- name: Setup main Docker host
  hosts: docker.home.remigourdon.net
  become: yes
  vars_files:
    - vars/cloudflare.yml
    - vars/gitea.yml
    - vars/drone.yml
    - vars/paperless.yml
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - traefik
        - heimdall
        - unifi
        - calibre-web
        - gitea
        - drone
        - registry
        - paperless
        - uptime-kuma
        - change-detection

- name: Setup builder Docker host for Drone
  hosts: builder.home.remigourdon.net
  become: yes
  vars_files:
    - vars/drone.yml
  vars:
    docker_domain: docker.home.remigourdon.net
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - drone-runner
