---
- name: Install common
  hosts: all
  become: yes
  roles:
    - role: common
    - role: update
      tags: update,never

- name: Setup pi-hole host
  hosts: froufrou.home.remigourdon.net
  tasks:
    - name: Configure Sysctl
      become: yes
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        ignoreerrors: true
        sysctl_set: true
    - name: Configure Tailscale as exit node and subnet router
      include_role:
        name: artis3n.tailscale
      vars:
        tailscale_args: "--advertise-exit-node --advertise-routes=192.168.50.0/24"

- name: Setup main Docker host
  hosts: docker.home.remigourdon.net
  become: yes
  vars_files:
    - vars/diun.yml
    - vars/cloudflare.yml
    - vars/gitea.yml
    - vars/drone.yml
    - vars/paperless.yml
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - diun
        - traefik
        - heimdall
        - unifi
        - calibre-web
        - gitea
        - drone
        - registry
        - paperless

- name: Setup builder Docker host for Drone
  hosts: builder.home.remigourdon.net
  become: yes
  vars_files:
    - vars/diun.yml
    - vars/drone.yml
  vars:
    docker_domain: docker.home.remigourdon.net
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - diun
        - drone-runner
