---
- name: Install common
  hosts: all
  become: yes
  roles:
    - role: common
    - role: update
      tags: update,never

- name: Setup main Docker host
  hosts: docker.home.remigourdon.net
  become: yes
  vars_files:
    - vars/diun.yml
    - vars/cloudflare.yml
    - vars/nextcloud.yml
    - vars/gitea.yml
    - vars/drone.yml
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - diun
        - traefik
        - heimdall
        - unifi
        - calibre-web
        - nextcloud
        - gitea
        - drone
        - registry

- name: Setup builder Docker host for Drone
  hosts: builder.home.remigourdon.net
  become: yes
  vars_files:
    - vars/diun.yml
    - vars/drone.yml
  vars:
    docker_domain: docker.home.remigourdon.net
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - diun
        - drone-runner
