---
- name: Install common
  hosts: all
  become: yes
  roles:
    - role: common
    - role: update
      tags: update,never

- name: Setup tailscale
  hosts: tailscale
  become: yes
  tasks:
    - name: Configure Sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        ignoreerrors: true
        sysctl_set: true
      when: tailscale_subnet_router
    - name: Configure Tailscale
      include_role:
        name: artis3n.tailscale

- name: Setup main Docker host
  hosts: docker.home.remigourdon.net
  become: yes
  vars_files:
    - vars/cloudflare.yml
    - vars/paperless.yml
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - traefik
        - heimdall
        - unifi
        - calibre-web
        - paperless

- name: Setup Docker host for Windmill
  hosts: windmill.home.remigourdon.net
  become: yes
  roles:
    - role: docker
    - role: docker-compose
      project_names: []
