---
- name: Install common
  hosts: all
  become: yes
  roles:
    - role: common
    - role: update
      tags: update,never

- name: Setup main Docker host
  hosts: docker.home.remigourdon.net
  become: yes
  vars_files:
    - vars/cloudflare.yml
    - vars/paperless.yml
  roles:
    - role: docker
    - role: docker-compose
      project_names:
        - traefik
        - heimdall
        - unifi
        - calibre-web
        - paperless
