---
- name: Install common
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Docker host
  hosts: docker.home.remigourdon.net
  become: yes
  roles:
    - docker
    - unifi
    - heimdall