---
- name: Provision VMs in Proxmox
  hosts: vms
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - provision_vm

- name: Secure VMs login
  hosts: vms
  gather_facts: no
  become: yes
  roles:
    - secure_login
  pre_tasks:
    - name: Wait for connection to be available
      wait_for_connection:
        timeout: 60