---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: truenas-nfs
  namespace: democratic-csi
spec:
  interval: 10m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi
      interval: 15m
  valuesFrom:
    - kind: ConfigMap
      name: democratic-csi-config
      valuesKey: truenas-nfs-config.yaml
    - kind: Secret
      name: democratic-csi-secrets
      valuesKey: password
      targetPath: driver.config.httpConnection.password