---
- name: Stop VM
  proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ vm_id }}"
    timeout: 60
    state: stopped
  notify: sleep

- meta: flush_handlers

- name: Destroy VM
  proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    vmid: "{{ vm_id }}"
    timeout: 60
    state: absent
  notify: sleep