---
- debug:
    msg: "Installing {{ project_name }}"

- name: Create project directory
  file:
    path: "{{ project_dir_root }}/{{ project_name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Copy Docker Compose template
  template:
    src: "{{ project_template_dir }}/{{ project_name }}.yml.j2"
    dest: "{{ project_dir_root }}/{{ project_name }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir_root }}/{{ project_name }}"
    state: present
    pull: "{{ docker_pull | default('missing') }}"
