---
- name: Install Docker Compose with Python
  pip:
    name: docker-compose
    state: absent

- name: Set up compose projects
  include_tasks: compose-project.yml
  loop: "{{ project_names }}"
  loop_control:
    loop_var: project_name
