---
# Based on kube-vip K3s guide: https://kube-vip.io/docs/usage/k3s/

- name: Create manifests directory on first server node
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['k3s_servers'][0]]['ansible_hostname']

- name: Copy kube-vip RBAC manifest to first server node
  template:
    src: kube-vip-rbac.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['k3s_servers'][0]]['ansible_hostname']

- name: Copy kube-vip manifest to first server node
  template:
    src: kube-vip.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip.yaml
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['k3s_servers'][0]]['ansible_hostname']

- name: Copy kube-vip Cloud Controller manifest to first server node
  template:
    src: kube-vip-cloud-controller.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-cloud-controller.yaml
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['k3s_servers'][0]]['ansible_hostname']

- name: Initialize cluster on first server node
  command:
    cmd: >
      systemd-run
        --property RestartSec=2
        --property Restart=on-failure
        --unit=k3s-init
        k3s server
          --cluster-init
          --token "{{ k3s_token }}"
          --tls-san {{ kube_vip_ip }}
          --disable servicelb
          --disable traefik
    creates: /etc/systemd/system/k3s.service
  args:
    warn: false  # The ansible systemd module does not support transient units
  when: ansible_hostname == hostvars[groups['k3s_servers'][0]]['ansible_hostname']

- name: Join other server nodes to cluster
  command:
    cmd: >
      systemd-run
        --property RestartSec=2
        --property Restart=on-failure
        --unit=k3s-init
        k3s server
          --server "https://{{ hostvars[groups['k3s_servers'][0]].k3s_node_ip }}:6443"
          --token "{{ k3s_token }}"
          --tls-san {{ kube_vip_ip }}
          --disable servicelb
          --disable traefik
    creates: /etc/systemd/system/k3s.service
  args:
    warn: false  # The ansible systemd module does not support transient units
  when: ansible_hostname != hostvars[groups['k3s_servers'][0]]['ansible_hostname']