---
k3s_server_first_arg: >-
  {%- if ansible_hostname == hostvars[groups['k3s_servers'][0]]['ansible_hostname'] -%}
    --cluster-init
  {%- else -%}
    --server https://{{ hostvars[groups['k3s_servers'][0]].k3s_node_ip }}:6443
  {%- endif -%}