---
- name: Disable empty password login
  lineinfile: 
    dest: "{{ sshd_config }}" 
    regexp: '^#?PermitEmptyPasswords' 
    line: 'PermitEmptyPasswords no'
  notify: restart sshd

- name: Disable remote root login
  lineinfile: 
    dest: "{{ sshd_config }}" 
    regexp: '^#?PermitRootLogin' 
    line: 'PermitRootLogin no'
  notify: restart sshd

- name: Disable password login
  lineinfile: 
    dest: "{{ sshd_config }}" 
    regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'
  notify: restart sshd