---
- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip # For Docker SDK and Docker Compose
    state: present

- name: Add Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker package repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    update_cache: yes
    state: present

- name: Install Docker engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  notify: restart Docker service

- name: Allow user to access Docker socket
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present
  notify: restart Docker service

- name: Prune Docker images
  docker_prune:
    images: yes
    images_filters:
      dangling: false
