---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s/reset
  post_tasks:
    - name: Reboot and wait for node to come back up
      reboot:
        reboot_timeout: 3600
